### PR TITLE
chore(deps): move jest to dev dependencies

### PR DESCRIPTION
**Pull request by ike18t**

### CODE REVIEW

**Comment by matti-o7** [comment]
I need this!

**Review by mttigg — APPROVED** [review]

**Comment by jwarby** [comment]
Hi @ike18t, thanks for this!

Sorry for the massive delay - I've just been going through notifications on the GitHub UI and I've come across a few PRs that I didn't receive email notifications for.

I'll set a reminder to look at this over the weekend to get it merged in and get a new release pushed out.

FYI @matti-o7

**Comment by ike18t** [comment]
No problem! Trivial change but I ran into the same issue that @matti-o7 ran into with CRA.

**Comment by jwarby** [comment]
Hi @ike18t, @matti-o7  I've released [v1.0.2](https://www.npmjs.com/package/inquirer-maxlength-input-prompt/v/1.0.2) this morning. Thanks both!

**Pull request merged**
